db.ojs.intra:
  image: mysql:5.6
  volumes:
    - ./.docker/ojs-mysql-data:/var/lib/mysql
  env_file: local.ENV

memcached.ojs.intra:
  image: memcached

ojs.intra:
  image: sorinbadea/ojs
  env_file: local.ENV
  ports:
    - 4562:80
  links:
    - db.ojs.intra
    - memcached.ojs.intra
  volumes:
    - ./.docker/ojs-files:/opt/files
